<?php
// $Id$

/**
 * @file
 *
 * Enables mautic tracker
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path 
 *   Which path of the site we're using to display help
 * @param arg 
 *   Array that holds the current path as returned from arg() function
 */
function mautic_tracker_help($path, $arg) {
  switch ($path) {
    case "admin/help#mautic_tracker":
      return '<p>' . t("Tracker for mautic") . '</p>';
      break;
  }
}

/**
 * Implements hook_menu().
 */
function mautic_tracker_menu() {
  $items = array();

  $items['admin/config/mautic'] = array(
    'title' => 'Mautic URL',
    'description' => 'Configuration for Current posts module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('mautic_tracker_form'),
    'access arguments' => array('access administration pages'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

function mautic_tracker_form() {
  $form = array();

  $form['mautic_base_url'] = array(
    '#type' => 'textfield',
    '#title' => t('Mautic URL'),
    '#default_value' => variable_get('mautic_base_url', ''),
    '#size' => 60,
    '#description' => t("Your mautic base url."),
    '#required' => TRUE,
  );

  $form['mautic_load_form_js'] = array(
    '#type' => 'checkbox',
    '#title' => t('Use Mautic Forms'),
    '#default_value' => variable_get('mautic_load_form_js', ''),
    '#description' => t("If you want to embed a Mautic Form, it is necessary to load a JavaScript file."),
    '#required' => FALSE,
  );

  if (variable_get('mautic_load_form_js', '')) {
    $form['mautic_shortcode_example'] = array(
      '#type' => 'textfield',
      '#title' => t('Mautic Form Shortcode'),
      '#default_value' => '{mauticform id=1 width=300px height=300px}',
      '#description' => t("Insert the shortcode to your content. Mautic Form JavaScript will replace this code with iframe of Mautic form with ID 1. Change the ID to the ID of the for you want to load. You can change width and height as your for needs."),
      '#required' => FALSE,
      '#disabled' => TRUE
    );
  }

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function mautic_tracker_block_info() {
  $blocks = array();

  $blocks['mautic_tracker'] = array(
    'info' => t('Mautic Tracker.'),
    'cache' => DRUPAL_NO_CACHE,
  );

  return $blocks;
}

function mautic_tracker_block_view($delta = '') {
  switch ($delta) {
    case 'mautic_tracker':

      global $language;
      global $base_root;

      $current_url        = $base_root . request_uri();

      // Get additional data to send
      $attrs = array();
      $attrs['title']     = drupal_get_title();
      $attrs['language']  = $language->language;
      $attrs['referrer']  = isset($_SERVER['HTTP_REFERER']) ? $_SERVER['HTTP_REFERER'] : $current_url;
      $attrs['url']       = $current_url;

      $encodedAttrs       = urlencode(base64_encode(serialize($attrs)));
      $mautic_base_url    = trim(variable_get('mautic_base_url', ''), ' \t\n\r\0\x0B/');

      if (variable_get('mautic_load_form_js', 0)) {
        $formJs           = '<script src="%1$s/media/js/mautic-form.js?modal_css=0"></script>';
      } else {
        $formJs           = '';
      }

      $block['content']   = sprintf('<img style="display:none" src="%s/mtracking.gif?d=%s" />' . $formJs, $mautic_base_url, $encodedAttrs);

      return $block;
      break; 
  }
}
